//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    //DbContext -  the database connection and a set of tables.
    public partial class MyDataBaseSampleEntities : DbContext
    {
        public MyDataBaseSampleEntities()
            : base("name=MyDataBaseSampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        //DbSet as a representation of the tables themselves
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
