// <auto-generated />
namespace Car_Rental_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class workprocessmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workprocessmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201901110909364_work-process migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
